Unit tests
captainspain/web-terminal pull request #10
Opened 2018-10-05 17:19 UTC by misantron

- Unit tests for Logger, Request and Session classes
- Logger refactoring (use SplFileObject instead of file_get_contents/file_put_contents)
- Bug fixes

2018-10-05 22:24 UTC, misantron commented
Waiting for code review

2018-10-06 09:00 UTC, captainspain requested changes
Thanks a lot for this PR.
Looks good to me, only 2 minor issues. If you can fix them I will merge it :)

2018-10-06 09:00 UTC, captainspain commented on src/WebTerminal/Logger.php
> +    public function __construct(string $filePath)
This constructor should not throw an Exception if file not found it should create one.

2018-10-06 09:00 UTC, captainspain commented on src/WebTerminal/Logger.php
> +        $file->rewind();
The rewind function is triggering a Warning: `SplFileObject::rewind(): stream does not support seeking`

2018-10-06 09:50 UTC, misantron commented on src/WebTerminal/Logger.php
> +    public function __construct(string $filePath)
Ok but what should we do if the file is not readable?

2018-10-06 12:53 UTC, captainspain commented on src/WebTerminal/Logger.php
> +    public function __construct(string $filePath)
@misantron create a new file. If that's not possible then throw one

2018-10-06 14:14 UTC, misantron commented on src/WebTerminal/Logger.php
> +    public function __construct(string $filePath)
@captainspain rollback SplFileObject usage. We get more problems than we solve.

2018-10-06 14:47 UTC, captainspain approved these changes

2018-10-06 14:49 UTC, merged

2018-10-06 14:49 UTC, captainspain commented
Thanks a lot @misantron